import Foundation

/// Base de datos local de modelos de iPhone, indexada por el identificador
/// interno de hardware (`hw.machine`, p.ej. "iPhone15,2").
///
/// Apple no expone ninguna API pública que devuelva estas capacidades
/// (número de cámaras, LiDAR, Dynamic Island, etc.) a partir del
/// identificador de hardware: por eso se mantiene esta tabla, construida a
/// partir de las especificaciones técnicas publicadas por Apple para cada
/// modelo. Si Apple lanza un modelo nuevo no incluido aquí,
/// `DeviceInfoManager` aplica una estimación conservadora basada en
/// capacidades detectables en tiempo de ejecución (ver `DeviceInfoManager.fallbackModel`).
enum DeviceDatabase {

    static let models: [String: DeviceModel] = {
        var all: [String: DeviceModel] = [:]
        for model in allModels {
            all[model.identifier] = model
        }
        return all
    }()

    static func model(for identifier: String) -> DeviceModel? {
        models[identifier]
    }

    // MARK: - Listado completo

    static let allModels: [DeviceModel] = [
        // iPhone 5s
        DeviceModel(identifier: "iPhone6,1", marketingName: "iPhone 5s", year: 2013, chip: "Apple A7",
                    screenSizeInches: 4.0, hasTrueTone: false, hasProMotion: false, hasDynamicIsland: false, hasAlwaysOnDisplay: false,
                    hasFaceID: false, hasTouchID: true, touchIDLocation: .home,
                    rearCameraCount: 1, hasUltraWideCamera: false, hasTelephotoCamera: false, hasMacroCamera: false, hasLiDAR: false, hasOpticalZoom: false,
                    connector: .lightning, supportsMagSafe: false, supportsWirelessCharging: false, supportsFastCharging: false, hasNFC: false, hasUltraWideband: false,
                    hasBarometer: false, hasGyroscope: true, hasCompass: true, hasProximitySensor: true, hasAmbientLightSensor: true,
                    hasActionButton: false, hasHomeButton: true, hasMuteSwitch: true,
                    hasStereoSpeakers: false, microphoneCount: 1),
        DeviceModel(identifier: "iPhone6,2", marketingName: "iPhone 5s", year: 2013, chip: "Apple A7",
                    screenSizeInches: 4.0, hasTrueTone: false, hasProMotion: false, hasDynamicIsland: false, hasAlwaysOnDisplay: false,
                    hasFaceID: false, hasTouchID: true, touchIDLocation: .home,
                    rearCameraCount: 1, hasUltraWideCamera: false, hasTelephotoCamera: false, hasMacroCamera: false, hasLiDAR: false, hasOpticalZoom: false,
                    connector: .lightning, supportsMagSafe: false, supportsWirelessCharging: false, supportsFastCharging: false, hasNFC: false, hasUltraWideband: false,
                    hasBarometer: false, hasGyroscope: true, hasCompass: true, hasProximitySensor: true, hasAmbientLightSensor: true,
                    hasActionButton: false, hasHomeButton: true, hasMuteSwitch: true,
                    hasStereoSpeakers: false, microphoneCount: 1),

        // iPhone 6 / 6 Plus
        DeviceModel(identifier: "iPhone7,2", marketingName: "iPhone 6", year: 2014, chip: "Apple A8",
                    screenSizeInches: 4.7, hasTrueTone: false, hasProMotion: false, hasDynamicIsland: false, hasAlwaysOnDisplay: false,
                    hasFaceID: false, hasTouchID: true, touchIDLocation: .home,
                    rearCameraCount: 1, hasUltraWideCamera: false, hasTelephotoCamera: false, hasMacroCamera: false, hasLiDAR: false, hasOpticalZoom: false,
                    connector: .lightning, supportsMagSafe: false, supportsWirelessCharging: false, supportsFastCharging: false, hasNFC: true, hasUltraWideband: false,
                    hasBarometer: true, hasGyroscope: true, hasCompass: true, hasProximitySensor: true, hasAmbientLightSensor: true,
                    hasActionButton: false, hasHomeButton: true, hasMuteSwitch: true,
                    hasStereoSpeakers: false, microphoneCount: 2),
        DeviceModel(identifier: "iPhone7,1", marketingName: "iPhone 6 Plus", year: 2014, chip: "Apple A8",
                    screenSizeInches: 5.5, hasTrueTone: false, hasProMotion: false, hasDynamicIsland: false, hasAlwaysOnDisplay: false,
                    hasFaceID: false, hasTouchID: true, touchIDLocation: .home,
                    rearCameraCount: 1, hasUltraWideCamera: false, hasTelephotoCamera: false, hasMacroCamera: false, hasLiDAR: false, hasOpticalZoom: false,
                    connector: .lightning, supportsMagSafe: false, supportsWirelessCharging: false, supportsFastCharging: false, hasNFC: true, hasUltraWideband: false,
                    hasBarometer: true, hasGyroscope: true, hasCompass: true, hasProximitySensor: true, hasAmbientLightSensor: true,
                    hasActionButton: false, hasHomeButton: true, hasMuteSwitch: true,
                    hasStereoSpeakers: false, microphoneCount: 2),

        // iPhone 6s / 6s Plus / SE (1st gen)
        DeviceModel(identifier: "iPhone8,1", marketingName: "iPhone 6s", year: 2015, chip: "Apple A9",
                    screenSizeInches: 4.7, hasTrueTone: false, hasProMotion: false, hasDynamicIsland: false, hasAlwaysOnDisplay: false,
                    hasFaceID: false, hasTouchID: true, touchIDLocation: .home,
                    rearCameraCount: 1, hasUltraWideCamera: false, hasTelephotoCamera: false, hasMacroCamera: false, hasLiDAR: false, hasOpticalZoom: false,
                    connector: .lightning, supportsMagSafe: false, supportsWirelessCharging: false, supportsFastCharging: false, hasNFC: true, hasUltraWideband: false,
                    hasBarometer: true, hasGyroscope: true, hasCompass: true, hasProximitySensor: true, hasAmbientLightSensor: true,
                    hasActionButton: false, hasHomeButton: true, hasMuteSwitch: true,
                    hasStereoSpeakers: false, microphoneCount: 2),
        DeviceModel(identifier: "iPhone8,2", marketingName: "iPhone 6s Plus", year: 2015, chip: "Apple A9",
                    screenSizeInches: 5.5, hasTrueTone: false, hasProMotion: false, hasDynamicIsland: false, hasAlwaysOnDisplay: false,
                    hasFaceID: false, hasTouchID: true, touchIDLocation: .home,
                    rearCameraCount: 1, hasUltraWideCamera: false, hasTelephotoCamera: false, hasMacroCamera: false, hasLiDAR: false, hasOpticalZoom: false,
                    connector: .lightning, supportsMagSafe: false, supportsWirelessCharging: false, supportsFastCharging: false, hasNFC: true, hasUltraWideband: false,
                    hasBarometer: true, hasGyroscope: true, hasCompass: true, hasProximitySensor: true, hasAmbientLightSensor: true,
                    hasActionButton: false, hasHomeButton: true, hasMuteSwitch: true,
                    hasStereoSpeakers: false, microphoneCount: 2),
        DeviceModel(identifier: "iPhone8,4", marketingName: "iPhone SE (1.ª gen.)", year: 2016, chip: "Apple A9",
                    screenSizeInches: 4.0, hasTrueTone: false, hasProMotion: false, hasDynamicIsland: false, hasAlwaysOnDisplay: false,
                    hasFaceID: false, hasTouchID: true, touchIDLocation: .home,
                    rearCameraCount: 1, hasUltraWideCamera: false, hasTelephotoCamera: false, hasMacroCamera: false, hasLiDAR: false, hasOpticalZoom: false,
                    connector: .lightning, supportsMagSafe: false, supportsWirelessCharging: false, supportsFastCharging: false, hasNFC: true, hasUltraWideband: false,
                    hasBarometer: true, hasGyroscope: true, hasCompass: true, hasProximitySensor: true, hasAmbientLightSensor: true,
                    hasActionButton: false, hasHomeButton: true, hasMuteSwitch: true,
                    hasStereoSpeakers: false, microphoneCount: 2),

        // iPhone 7 / 7 Plus
        DeviceModel(identifier: "iPhone9,1", marketingName: "iPhone 7", year: 2016, chip: "Apple A10 Fusion",
                    screenSizeInches: 4.7, hasTrueTone: true, hasProMotion: false, hasDynamicIsland: false, hasAlwaysOnDisplay: false,
                    hasFaceID: false, hasTouchID: true, touchIDLocation: .home,
                    rearCameraCount: 1, hasUltraWideCamera: false, hasTelephotoCamera: false, hasMacroCamera: false, hasLiDAR: false, hasOpticalZoom: false,
                    connector: .lightning, supportsMagSafe: false, supportsWirelessCharging: false, supportsFastCharging: false, hasNFC: true, hasUltraWideband: false,
                    hasBarometer: true, hasGyroscope: true, hasCompass: true, hasProximitySensor: true, hasAmbientLightSensor: true,
                    hasActionButton: false, hasHomeButton: true, hasMuteSwitch: true,
                    hasStereoSpeakers: true, microphoneCount: 2),
        DeviceModel(identifier: "iPhone9,3", marketingName: "iPhone 7", year: 2016, chip: "Apple A10 Fusion",
                    screenSizeInches: 4.7, hasTrueTone: true, hasProMotion: false, hasDynamicIsland: false, hasAlwaysOnDisplay: false,
                    hasFaceID: false, hasTouchID: true, touchIDLocation: .home,
                    rearCameraCount: 1, hasUltraWideCamera: false, hasTelephotoCamera: false, hasMacroCamera: false, hasLiDAR: false, hasOpticalZoom: false,
                    connector: .lightning, supportsMagSafe: false, supportsWirelessCharging: false, supportsFastCharging: false, hasNFC: true, hasUltraWideband: false,
                    hasBarometer: true, hasGyroscope: true, hasCompass: true, hasProximitySensor: true, hasAmbientLightSensor: true,
                    hasActionButton: false, hasHomeButton: true, hasMuteSwitch: true,
                    hasStereoSpeakers: true, microphoneCount: 2),
        DeviceModel(identifier: "iPhone9,2", marketingName: "iPhone 7 Plus", year: 2016, chip: "Apple A10 Fusion",
                    screenSizeInches: 5.5, hasTrueTone: true, hasProMotion: false, hasDynamicIsland: false, hasAlwaysOnDisplay: false,
                    hasFaceID: false, hasTouchID: true, touchIDLocation: .home,
                    rearCameraCount: 2, hasUltraWideCamera: false, hasTelephotoCamera: true, hasMacroCamera: false, hasLiDAR: false, hasOpticalZoom: true,
                    connector: .lightning, supportsMagSafe: false, supportsWirelessCharging: false, supportsFastCharging: false, hasNFC: true, hasUltraWideband: false,
                    hasBarometer: true, hasGyroscope: true, hasCompass: true, hasProximitySensor: true, hasAmbientLightSensor: true,
                    hasActionButton: false, hasHomeButton: true, hasMuteSwitch: true,
                    hasStereoSpeakers: true, microphoneCount: 2),
        DeviceModel(identifier: "iPhone9,4", marketingName: "iPhone 7 Plus", year: 2016, chip: "Apple A10 Fusion",
                    screenSizeInches: 5.5, hasTrueTone: true, hasProMotion: false, hasDynamicIsland: false, hasAlwaysOnDisplay: false,
                    hasFaceID: false, hasTouchID: true, touchIDLocation: .home,
                    rearCameraCount: 2, hasUltraWideCamera: false, hasTelephotoCamera: true, hasMacroCamera: false, hasLiDAR: false, hasOpticalZoom: true,
                    connector: .lightning, supportsMagSafe: false, supportsWirelessCharging: false, supportsFastCharging: false, hasNFC: true, hasUltraWideband: false,
                    hasBarometer: true, hasGyroscope: true, hasCompass: true, hasProximitySensor: true, hasAmbientLightSensor: true,
                    hasActionButton: false, hasHomeButton: true, hasMuteSwitch: true,
                    hasStereoSpeakers: true, microphoneCount: 2),

        // iPhone 8 / 8 Plus / X
        DeviceModel(identifier: "iPhone10,1", marketingName: "iPhone 8", year: 2017, chip: "Apple A11 Bionic",
                    screenSizeInches: 4.7, hasTrueTone: true, hasProMotion: false, hasDynamicIsland: false, hasAlwaysOnDisplay: false,
                    hasFaceID: false, hasTouchID: true, touchIDLocation: .home,
                    rearCameraCount: 1, hasUltraWideCamera: false, hasTelephotoCamera: false, hasMacroCamera: false, hasLiDAR: false, hasOpticalZoom: false,
                    connector: .lightning, supportsMagSafe: false, supportsWirelessCharging: true, supportsFastCharging: true, hasNFC: true, hasUltraWideband: false,
                    hasBarometer: true, hasGyroscope: true, hasCompass: true, hasProximitySensor: true, hasAmbientLightSensor: true,
                    hasActionButton: false, hasHomeButton: true, hasMuteSwitch: true,
                    hasStereoSpeakers: true, microphoneCount: 2),
        DeviceModel(identifier: "iPhone10,4", marketingName: "iPhone 8", year: 2017, chip: "Apple A11 Bionic",
                    screenSizeInches: 4.7, hasTrueTone: true, hasProMotion: false, hasDynamicIsland: false, hasAlwaysOnDisplay: false,
                    hasFaceID: false, hasTouchID: true, touchIDLocation: .home,
                    rearCameraCount: 1, hasUltraWideCamera: false, hasTelephotoCamera: false, hasMacroCamera: false, hasLiDAR: false, hasOpticalZoom: false,
                    connector: .lightning, supportsMagSafe: false, supportsWirelessCharging: true, supportsFastCharging: true, hasNFC: true, hasUltraWideband: false,
                    hasBarometer: true, hasGyroscope: true, hasCompass: true, hasProximitySensor: true, hasAmbientLightSensor: true,
                    hasActionButton: false, hasHomeButton: true, hasMuteSwitch: true,
                    hasStereoSpeakers: true, microphoneCount: 2),
        DeviceModel(identifier: "iPhone10,2", marketingName: "iPhone 8 Plus", year: 2017, chip: "Apple A11 Bionic",
                    screenSizeInches: 5.5, hasTrueTone: true, hasProMotion: false, hasDynamicIsland: false, hasAlwaysOnDisplay: false,
                    hasFaceID: false, hasTouchID: true, touchIDLocation: .home,
                    rearCameraCount: 2, hasUltraWideCamera: false, hasTelephotoCamera: true, hasMacroCamera: false, hasLiDAR: false, hasOpticalZoom: true,
                    connector: .lightning, supportsMagSafe: false, supportsWirelessCharging: true, supportsFastCharging: true, hasNFC: true, hasUltraWideband: false,
                    hasBarometer: true, hasGyroscope: true, hasCompass: true, hasProximitySensor: true, hasAmbientLightSensor: true,
                    hasActionButton: false, hasHomeButton: true, hasMuteSwitch: true,
                    hasStereoSpeakers: true, microphoneCount: 2),
        DeviceModel(identifier: "iPhone10,5", marketingName: "iPhone 8 Plus", year: 2017, chip: "Apple A11 Bionic",
                    screenSizeInches: 5.5, hasTrueTone: true, hasProMotion: false, hasDynamicIsland: false, hasAlwaysOnDisplay: false,
                    hasFaceID: false, hasTouchID: true, touchIDLocation: .home,
                    rearCameraCount: 2, hasUltraWideCamera: false, hasTelephotoCamera: true, hasMacroCamera: false, hasLiDAR: false, hasOpticalZoom: true,
                    connector: .lightning, supportsMagSafe: false, supportsWirelessCharging: true, supportsFastCharging: true, hasNFC: true, hasUltraWideband: false,
                    hasBarometer: true, hasGyroscope: true, hasCompass: true, hasProximitySensor: true, hasAmbientLightSensor: true,
                    hasActionButton: false, hasHomeButton: true, hasMuteSwitch: true,
                    hasStereoSpeakers: true, microphoneCount: 2),
        DeviceModel(identifier: "iPhone10,3", marketingName: "iPhone X", year: 2017, chip: "Apple A11 Bionic",
                    screenSizeInches: 5.8, hasTrueTone: true, hasProMotion: false, hasDynamicIsland: false, hasAlwaysOnDisplay: false,
                    hasFaceID: true, hasTouchID: false, touchIDLocation: .none,
                    rearCameraCount: 2, hasUltraWideCamera: false, hasTelephotoCamera: true, hasMacroCamera: false, hasLiDAR: false, hasOpticalZoom: true,
                    connector: .lightning, supportsMagSafe: false, supportsWirelessCharging: true, supportsFastCharging: true, hasNFC: true, hasUltraWideband: false,
                    hasBarometer: true, hasGyroscope: true, hasCompass: true, hasProximitySensor: true, hasAmbientLightSensor: true,
                    hasActionButton: false, hasHomeButton: false, hasMuteSwitch: true,
                    hasStereoSpeakers: true, microphoneCount: 2),
        DeviceModel(identifier: "iPhone10,6", marketingName: "iPhone X", year: 2017, chip: "Apple A11 Bionic",
                    screenSizeInches: 5.8, hasTrueTone: true, hasProMotion: false, hasDynamicIsland: false, hasAlwaysOnDisplay: false,
                    hasFaceID: true, hasTouchID: false, touchIDLocation: .none,
                    rearCameraCount: 2, hasUltraWideCamera: false, hasTelephotoCamera: true, hasMacroCamera: false, hasLiDAR: false, hasOpticalZoom: true,
                    connector: .lightning, supportsMagSafe: false, supportsWirelessCharging: true, supportsFastCharging: true, hasNFC: true, hasUltraWideband: false,
                    hasBarometer: true, hasGyroscope: true, hasCompass: true, hasProximitySensor: true, hasAmbientLightSensor: true,
                    hasActionButton: false, hasHomeButton: false, hasMuteSwitch: true,
                    hasStereoSpeakers: true, microphoneCount: 2),

        // iPhone XS / XS Max / XR
        DeviceModel(identifier: "iPhone11,2", marketingName: "iPhone XS", year: 2018, chip: "Apple A12 Bionic",
                    screenSizeInches: 5.8, hasTrueTone: true, hasProMotion: false, hasDynamicIsland: false, hasAlwaysOnDisplay: false,
                    hasFaceID: true, hasTouchID: false, touchIDLocation: .none,
                    rearCameraCount: 2, hasUltraWideCamera: false, hasTelephotoCamera: true, hasMacroCamera: false, hasLiDAR: false, hasOpticalZoom: true,
                    connector: .lightning, supportsMagSafe: false, supportsWirelessCharging: true, supportsFastCharging: true, hasNFC: true, hasUltraWideband: false,
                    hasBarometer: true, hasGyroscope: true, hasCompass: true, hasProximitySensor: true, hasAmbientLightSensor: true,
                    hasActionButton: false, hasHomeButton: false, hasMuteSwitch: true,
                    hasStereoSpeakers: true, microphoneCount: 2),
        DeviceModel(identifier: "iPhone11,4", marketingName: "iPhone XS Max", year: 2018, chip: "Apple A12 Bionic",
                    screenSizeInches: 6.5, hasTrueTone: true, hasProMotion: false, hasDynamicIsland: false, hasAlwaysOnDisplay: false,
                    hasFaceID: true, hasTouchID: false, touchIDLocation: .none,
                    rearCameraCount: 2, hasUltraWideCamera: false, hasTelephotoCamera: true, hasMacroCamera: false, hasLiDAR: false, hasOpticalZoom: true,
                    connector: .lightning, supportsMagSafe: false, supportsWirelessCharging: true, supportsFastCharging: true, hasNFC: true, hasUltraWideband: false,
                    hasBarometer: true, hasGyroscope: true, hasCompass: true, hasProximitySensor: true, hasAmbientLightSensor: true,
                    hasActionButton: false, hasHomeButton: false, hasMuteSwitch: true,
                    hasStereoSpeakers: true, microphoneCount: 2),
        DeviceModel(identifier: "iPhone11,6", marketingName: "iPhone XS Max", year: 2018, chip: "Apple A12 Bionic",
                    screenSizeInches: 6.5, hasTrueTone: true, hasProMotion: false, hasDynamicIsland: false, hasAlwaysOnDisplay: false,
                    hasFaceID: true, hasTouchID: false, touchIDLocation: .none,
                    rearCameraCount: 2, hasUltraWideCamera: false, hasTelephotoCamera: true, hasMacroCamera: false, hasLiDAR: false, hasOpticalZoom: true,
                    connector: .lightning, supportsMagSafe: false, supportsWirelessCharging: true, supportsFastCharging: true, hasNFC: true, hasUltraWideband: false,
                    hasBarometer: true, hasGyroscope: true, hasCompass: true, hasProximitySensor: true, hasAmbientLightSensor: true,
                    hasActionButton: false, hasHomeButton: false, hasMuteSwitch: true,
                    hasStereoSpeakers: true, microphoneCount: 2),
        DeviceModel(identifier: "iPhone11,8", marketingName: "iPhone XR", year: 2018, chip: "Apple A12 Bionic",
                    screenSizeInches: 6.1, hasTrueTone: true, hasProMotion: false, hasDynamicIsland: false, hasAlwaysOnDisplay: false,
                    hasFaceID: true, hasTouchID: false, touchIDLocation: .none,
                    rearCameraCount: 1, hasUltraWideCamera: false, hasTelephotoCamera: false, hasMacroCamera: false, hasLiDAR: false, hasOpticalZoom: false,
                    connector: .lightning, supportsMagSafe: false, supportsWirelessCharging: true, supportsFastCharging: true, hasNFC: true, hasUltraWideband: false,
                    hasBarometer: true, hasGyroscope: true, hasCompass: true, hasProximitySensor: true, hasAmbientLightSensor: true,
                    hasActionButton: false, hasHomeButton: false, hasMuteSwitch: true,
                    hasStereoSpeakers: true, microphoneCount: 2),

        // iPhone 11 / 11 Pro / 11 Pro Max / SE 2020
        DeviceModel(identifier: "iPhone12,1", marketingName: "iPhone 11", year: 2019, chip: "Apple A13 Bionic",
                    screenSizeInches: 6.1, hasTrueTone: true, hasProMotion: false, hasDynamicIsland: false, hasAlwaysOnDisplay: false,
                    hasFaceID: true, hasTouchID: false, touchIDLocation: .none,
                    rearCameraCount: 2, hasUltraWideCamera: true, hasTelephotoCamera: false, hasMacroCamera: false, hasLiDAR: false, hasOpticalZoom: false,
                    connector: .lightning, supportsMagSafe: false, supportsWirelessCharging: true, supportsFastCharging: true, hasNFC: true, hasUltraWideband: true,
                    hasBarometer: true, hasGyroscope: true, hasCompass: true, hasProximitySensor: true, hasAmbientLightSensor: true,
                    hasActionButton: false, hasHomeButton: false, hasMuteSwitch: true,
                    hasStereoSpeakers: true, microphoneCount: 3),
        DeviceModel(identifier: "iPhone12,3", marketingName: "iPhone 11 Pro", year: 2019, chip: "Apple A13 Bionic",
                    screenSizeInches: 5.8, hasTrueTone: true, hasProMotion: false, hasDynamicIsland: false, hasAlwaysOnDisplay: false,
                    hasFaceID: true, hasTouchID: false, touchIDLocation: .none,
                    rearCameraCount: 3, hasUltraWideCamera: true, hasTelephotoCamera: true, hasMacroCamera: false, hasLiDAR: false, hasOpticalZoom: true,
                    connector: .lightning, supportsMagSafe: false, supportsWirelessCharging: true, supportsFastCharging: true, hasNFC: true, hasUltraWideband: true,
                    hasBarometer: true, hasGyroscope: true, hasCompass: true, hasProximitySensor: true, hasAmbientLightSensor: true,
                    hasActionButton: false, hasHomeButton: false, hasMuteSwitch: true,
                    hasStereoSpeakers: true, microphoneCount: 4),
        DeviceModel(identifier: "iPhone12,5", marketingName: "iPhone 11 Pro Max", year: 2019, chip: "Apple A13 Bionic",
                    screenSizeInches: 6.5, hasTrueTone: true, hasProMotion: false, hasDynamicIsland: false, hasAlwaysOnDisplay: false,
                    hasFaceID: true, hasTouchID: false, touchIDLocation: .none,
                    rearCameraCount: 3, hasUltraWideCamera: true, hasTelephotoCamera: true, hasMacroCamera: false, hasLiDAR: false, hasOpticalZoom: true,
                    connector: .lightning, supportsMagSafe: false, supportsWirelessCharging: true, supportsFastCharging: true, hasNFC: true, hasUltraWideband: true,
                    hasBarometer: true, hasGyroscope: true, hasCompass: true, hasProximitySensor: true, hasAmbientLightSensor: true,
                    hasActionButton: false, hasHomeButton: false, hasMuteSwitch: true,
                    hasStereoSpeakers: true, microphoneCount: 4),
        DeviceModel(identifier: "iPhone12,8", marketingName: "iPhone SE (2.ª gen.)", year: 2020, chip: "Apple A13 Bionic",
                    screenSizeInches: 4.7, hasTrueTone: true, hasProMotion: false, hasDynamicIsland: false, hasAlwaysOnDisplay: false,
                    hasFaceID: false, hasTouchID: true, touchIDLocation: .home,
                    rearCameraCount: 1, hasUltraWideCamera: false, hasTelephotoCamera: false, hasMacroCamera: false, hasLiDAR: false, hasOpticalZoom: false,
                    connector: .lightning, supportsMagSafe: false, supportsWirelessCharging: true, supportsFastCharging: true, hasNFC: true, hasUltraWideband: false,
                    hasBarometer: true, hasGyroscope: true, hasCompass: true, hasProximitySensor: true, hasAmbientLightSensor: true,
                    hasActionButton: false, hasHomeButton: true, hasMuteSwitch: true,
                    hasStereoSpeakers: true, microphoneCount: 2),

        // iPhone 12 lineup
        DeviceModel(identifier: "iPhone13,1", marketingName: "iPhone 12 mini", year: 2020, chip: "Apple A14 Bionic",
                    screenSizeInches: 5.4, hasTrueTone: true, hasProMotion: false, hasDynamicIsland: false, hasAlwaysOnDisplay: false,
                    hasFaceID: true, hasTouchID: false, touchIDLocation: .none,
                    rearCameraCount: 2, hasUltraWideCamera: true, hasTelephotoCamera: false, hasMacroCamera: false, hasLiDAR: false, hasOpticalZoom: false,
                    connector: .lightning, supportsMagSafe: true, supportsWirelessCharging: true, supportsFastCharging: true, hasNFC: true, hasUltraWideband: true,
                    hasBarometer: true, hasGyroscope: true, hasCompass: true, hasProximitySensor: true, hasAmbientLightSensor: true,
                    hasActionButton: false, hasHomeButton: false, hasMuteSwitch: true,
                    hasStereoSpeakers: true, microphoneCount: 3),
        DeviceModel(identifier: "iPhone13,2", marketingName: "iPhone 12", year: 2020, chip: "Apple A14 Bionic",
                    screenSizeInches: 6.1, hasTrueTone: true, hasProMotion: false, hasDynamicIsland: false, hasAlwaysOnDisplay: false,
                    hasFaceID: true, hasTouchID: false, touchIDLocation: .none,
                    rearCameraCount: 2, hasUltraWideCamera: true, hasTelephotoCamera: false, hasMacroCamera: false, hasLiDAR: false, hasOpticalZoom: false,
                    connector: .lightning, supportsMagSafe: true, supportsWirelessCharging: true, supportsFastCharging: true, hasNFC: true, hasUltraWideband: true,
                    hasBarometer: true, hasGyroscope: true, hasCompass: true, hasProximitySensor: true, hasAmbientLightSensor: true,
                    hasActionButton: false, hasHomeButton: false, hasMuteSwitch: true,
                    hasStereoSpeakers: true, microphoneCount: 3),
        DeviceModel(identifier: "iPhone13,3", marketingName: "iPhone 12 Pro", year: 2020, chip: "Apple A14 Bionic",
                    screenSizeInches: 6.1, hasTrueTone: true, hasProMotion: false, hasDynamicIsland: false, hasAlwaysOnDisplay: false,
                    hasFaceID: true, hasTouchID: false, touchIDLocation: .none,
                    rearCameraCount: 3, hasUltraWideCamera: true, hasTelephotoCamera: true, hasMacroCamera: false, hasLiDAR: true, hasOpticalZoom: true,
                    connector: .lightning, supportsMagSafe: true, supportsWirelessCharging: true, supportsFastCharging: true, hasNFC: true, hasUltraWideband: true,
                    hasBarometer: true, hasGyroscope: true, hasCompass: true, hasProximitySensor: true, hasAmbientLightSensor: true,
                    hasActionButton: false, hasHomeButton: false, hasMuteSwitch: true,
                    hasStereoSpeakers: true, microphoneCount: 4),
        DeviceModel(identifier: "iPhone13,4", marketingName: "iPhone 12 Pro Max", year: 2020, chip: "Apple A14 Bionic",
                    screenSizeInches: 6.7, hasTrueTone: true, hasProMotion: false, hasDynamicIsland: false, hasAlwaysOnDisplay: false,
                    hasFaceID: true, hasTouchID: false, touchIDLocation: .none,
                    rearCameraCount: 3, hasUltraWideCamera: true, hasTelephotoCamera: true, hasMacroCamera: false, hasLiDAR: true, hasOpticalZoom: true,
                    connector: .lightning, supportsMagSafe: true, supportsWirelessCharging: true, supportsFastCharging: true, hasNFC: true, hasUltraWideband: true,
                    hasBarometer: true, hasGyroscope: true, hasCompass: true, hasProximitySensor: true, hasAmbientLightSensor: true,
                    hasActionButton: false, hasHomeButton: false, hasMuteSwitch: true,
                    hasStereoSpeakers: true, microphoneCount: 4),

        // iPhone 13 lineup + SE 2022
        DeviceModel(identifier: "iPhone14,4", marketingName: "iPhone 13 mini", year: 2021, chip: "Apple A15 Bionic",
                    screenSizeInches: 5.4, hasTrueTone: true, hasProMotion: false, hasDynamicIsland: false, hasAlwaysOnDisplay: false,
                    hasFaceID: true, hasTouchID: false, touchIDLocation: .none,
                    rearCameraCount: 2, hasUltraWideCamera: true, hasTelephotoCamera: false, hasMacroCamera: false, hasLiDAR: false, hasOpticalZoom: false,
                    connector: .lightning, supportsMagSafe: true, supportsWirelessCharging: true, supportsFastCharging: true, hasNFC: true, hasUltraWideband: true,
                    hasBarometer: true, hasGyroscope: true, hasCompass: true, hasProximitySensor: true, hasAmbientLightSensor: true,
                    hasActionButton: false, hasHomeButton: false, hasMuteSwitch: true,
                    hasStereoSpeakers: true, microphoneCount: 3),
        DeviceModel(identifier: "iPhone14,5", marketingName: "iPhone 13", year: 2021, chip: "Apple A15 Bionic",
                    screenSizeInches: 6.1, hasTrueTone: true, hasProMotion: false, hasDynamicIsland: false, hasAlwaysOnDisplay: false,
                    hasFaceID: true, hasTouchID: false, touchIDLocation: .none,
                    rearCameraCount: 2, hasUltraWideCamera: true, hasTelephotoCamera: false, hasMacroCamera: false, hasLiDAR: false, hasOpticalZoom: false,
                    connector: .lightning, supportsMagSafe: true, supportsWirelessCharging: true, supportsFastCharging: true, hasNFC: true, hasUltraWideband: true,
                    hasBarometer: true, hasGyroscope: true, hasCompass: true, hasProximitySensor: true, hasAmbientLightSensor: true,
                    hasActionButton: false, hasHomeButton: false, hasMuteSwitch: true,
                    hasStereoSpeakers: true, microphoneCount: 3),
        DeviceModel(identifier: "iPhone14,2", marketingName: "iPhone 13 Pro", year: 2021, chip: "Apple A15 Bionic",
                    screenSizeInches: 6.1, hasTrueTone: true, hasProMotion: true, hasDynamicIsland: false, hasAlwaysOnDisplay: false,
                    hasFaceID: true, hasTouchID: false, touchIDLocation: .none,
                    rearCameraCount: 3, hasUltraWideCamera: true, hasTelephotoCamera: true, hasMacroCamera: true, hasLiDAR: true, hasOpticalZoom: true,
                    connector: .lightning, supportsMagSafe: true, supportsWirelessCharging: true, supportsFastCharging: true, hasNFC: true, hasUltraWideband: true,
                    hasBarometer: true, hasGyroscope: true, hasCompass: true, hasProximitySensor: true, hasAmbientLightSensor: true,
                    hasActionButton: false, hasHomeButton: false, hasMuteSwitch: true,
                    hasStereoSpeakers: true, microphoneCount: 4),
        DeviceModel(identifier: "iPhone14,3", marketingName: "iPhone 13 Pro Max", year: 2021, chip: "Apple A15 Bionic",
                    screenSizeInches: 6.7, hasTrueTone: true, hasProMotion: true, hasDynamicIsland: false, hasAlwaysOnDisplay: false,
                    hasFaceID: true, hasTouchID: false, touchIDLocation: .none,
                    rearCameraCount: 3, hasUltraWideCamera: true, hasTelephotoCamera: true, hasMacroCamera: true, hasLiDAR: true, hasOpticalZoom: true,
                    connector: .lightning, supportsMagSafe: true, supportsWirelessCharging: true, supportsFastCharging: true, hasNFC: true, hasUltraWideband: true,
                    hasBarometer: true, hasGyroscope: true, hasCompass: true, hasProximitySensor: true, hasAmbientLightSensor: true,
                    hasActionButton: false, hasHomeButton: false, hasMuteSwitch: true,
                    hasStereoSpeakers: true, microphoneCount: 4),
        DeviceModel(identifier: "iPhone14,6", marketingName: "iPhone SE (3.ª gen.)", year: 2022, chip: "Apple A15 Bionic",
                    screenSizeInches: 4.7, hasTrueTone: true, hasProMotion: false, hasDynamicIsland: false, hasAlwaysOnDisplay: false,
                    hasFaceID: false, hasTouchID: true, touchIDLocation: .home,
                    rearCameraCount: 1, hasUltraWideCamera: false, hasTelephotoCamera: false, hasMacroCamera: false, hasLiDAR: false, hasOpticalZoom: false,
                    connector: .lightning, supportsMagSafe: false, supportsWirelessCharging: true, supportsFastCharging: true, hasNFC: true, hasUltraWideband: false,
                    hasBarometer: true, hasGyroscope: true, hasCompass: true, hasProximitySensor: true, hasAmbientLightSensor: true,
                    hasActionButton: false, hasHomeButton: true, hasMuteSwitch: true,
                    hasStereoSpeakers: true, microphoneCount: 2),

        // iPhone 14 lineup
        DeviceModel(identifier: "iPhone14,7", marketingName: "iPhone 14", year: 2022, chip: "Apple A15 Bionic",
                    screenSizeInches: 6.1, hasTrueTone: true, hasProMotion: false, hasDynamicIsland: false, hasAlwaysOnDisplay: false,
                    hasFaceID: true, hasTouchID: false, touchIDLocation: .none,
                    rearCameraCount: 2, hasUltraWideCamera: true, hasTelephotoCamera: false, hasMacroCamera: false, hasLiDAR: false, hasOpticalZoom: false,
                    connector: .lightning, supportsMagSafe: true, supportsWirelessCharging: true, supportsFastCharging: true, hasNFC: true, hasUltraWideband: true,
                    hasBarometer: true, hasGyroscope: true, hasCompass: true, hasProximitySensor: true, hasAmbientLightSensor: true,
                    hasActionButton: false, hasHomeButton: false, hasMuteSwitch: true,
                    hasStereoSpeakers: true, microphoneCount: 3),
        DeviceModel(identifier: "iPhone14,8", marketingName: "iPhone 14 Plus", year: 2022, chip: "Apple A15 Bionic",
                    screenSizeInches: 6.7, hasTrueTone: true, hasProMotion: false, hasDynamicIsland: false, hasAlwaysOnDisplay: false,
                    hasFaceID: true, hasTouchID: false, touchIDLocation: .none,
                    rearCameraCount: 2, hasUltraWideCamera: true, hasTelephotoCamera: false, hasMacroCamera: false, hasLiDAR: false, hasOpticalZoom: false,
                    connector: .lightning, supportsMagSafe: true, supportsWirelessCharging: true, supportsFastCharging: true, hasNFC: true, hasUltraWideband: true,
                    hasBarometer: true, hasGyroscope: true, hasCompass: true, hasProximitySensor: true, hasAmbientLightSensor: true,
                    hasActionButton: false, hasHomeButton: false, hasMuteSwitch: true,
                    hasStereoSpeakers: true, microphoneCount: 3),
        DeviceModel(identifier: "iPhone15,2", marketingName: "iPhone 14 Pro", year: 2022, chip: "Apple A16 Bionic",
                    screenSizeInches: 6.1, hasTrueTone: true, hasProMotion: true, hasDynamicIsland: true, hasAlwaysOnDisplay: true,
                    hasFaceID: true, hasTouchID: false, touchIDLocation: .none,
                    rearCameraCount: 3, hasUltraWideCamera: true, hasTelephotoCamera: true, hasMacroCamera: true, hasLiDAR: true, hasOpticalZoom: true,
                    connector: .lightning, supportsMagSafe: true, supportsWirelessCharging: true, supportsFastCharging: true, hasNFC: true, hasUltraWideband: true,
                    hasBarometer: true, hasGyroscope: true, hasCompass: true, hasProximitySensor: true, hasAmbientLightSensor: true,
                    hasActionButton: false, hasHomeButton: false, hasMuteSwitch: true,
                    hasStereoSpeakers: true, microphoneCount: 4),
        DeviceModel(identifier: "iPhone15,3", marketingName: "iPhone 14 Pro Max", year: 2022, chip: "Apple A16 Bionic",
                    screenSizeInches: 6.7, hasTrueTone: true, hasProMotion: true, hasDynamicIsland: true, hasAlwaysOnDisplay: true,
                    hasFaceID: true, hasTouchID: false, touchIDLocation: .none,
                    rearCameraCount: 3, hasUltraWideCamera: true, hasTelephotoCamera: true, hasMacroCamera: true, hasLiDAR: true, hasOpticalZoom: true,
                    connector: .lightning, supportsMagSafe: true, supportsWirelessCharging: true, supportsFastCharging: true, hasNFC: true, hasUltraWideband: true,
                    hasBarometer: true, hasGyroscope: true, hasCompass: true, hasProximitySensor: true, hasAmbientLightSensor: true,
                    hasActionButton: false, hasHomeButton: false, hasMuteSwitch: true,
                    hasStereoSpeakers: true, microphoneCount: 4),

        // iPhone 15 lineup
        DeviceModel(identifier: "iPhone15,4", marketingName: "iPhone 15", year: 2023, chip: "Apple A16 Bionic",
                    screenSizeInches: 6.1, hasTrueTone: true, hasProMotion: false, hasDynamicIsland: true, hasAlwaysOnDisplay: false,
                    hasFaceID: true, hasTouchID: false, touchIDLocation: .none,
                    rearCameraCount: 2, hasUltraWideCamera: true, hasTelephotoCamera: false, hasMacroCamera: false, hasLiDAR: false, hasOpticalZoom: false,
                    connector: .usbC, supportsMagSafe: true, supportsWirelessCharging: true, supportsFastCharging: true, hasNFC: true, hasUltraWideband: true,
                    hasBarometer: true, hasGyroscope: true, hasCompass: true, hasProximitySensor: true, hasAmbientLightSensor: true,
                    hasActionButton: false, hasHomeButton: false, hasMuteSwitch: true,
                    hasStereoSpeakers: true, microphoneCount: 3),
        DeviceModel(identifier: "iPhone15,5", marketingName: "iPhone 15 Plus", year: 2023, chip: "Apple A16 Bionic",
                    screenSizeInches: 6.7, hasTrueTone: true, hasProMotion: false, hasDynamicIsland: true, hasAlwaysOnDisplay: false,
                    hasFaceID: true, hasTouchID: false, touchIDLocation: .none,
                    rearCameraCount: 2, hasUltraWideCamera: true, hasTelephotoCamera: false, hasMacroCamera: false, hasLiDAR: false, hasOpticalZoom: false,
                    connector: .usbC, supportsMagSafe: true, supportsWirelessCharging: true, supportsFastCharging: true, hasNFC: true, hasUltraWideband: true,
                    hasBarometer: true, hasGyroscope: true, hasCompass: true, hasProximitySensor: true, hasAmbientLightSensor: true,
                    hasActionButton: false, hasHomeButton: false, hasMuteSwitch: true,
                    hasStereoSpeakers: true, microphoneCount: 3),
        DeviceModel(identifier: "iPhone16,1", marketingName: "iPhone 15 Pro", year: 2023, chip: "Apple A17 Pro",
                    screenSizeInches: 6.1, hasTrueTone: true, hasProMotion: true, hasDynamicIsland: true, hasAlwaysOnDisplay: true,
                    hasFaceID: true, hasTouchID: false, touchIDLocation: .none,
                    rearCameraCount: 3, hasUltraWideCamera: true, hasTelephotoCamera: true, hasMacroCamera: true, hasLiDAR: true, hasOpticalZoom: true,
                    connector: .usbC, supportsMagSafe: true, supportsWirelessCharging: true, supportsFastCharging: true, hasNFC: true, hasUltraWideband: true,
                    hasBarometer: true, hasGyroscope: true, hasCompass: true, hasProximitySensor: true, hasAmbientLightSensor: true,
                    hasActionButton: true, hasHomeButton: false, hasMuteSwitch: false,
                    hasStereoSpeakers: true, microphoneCount: 4),
        DeviceModel(identifier: "iPhone16,2", marketingName: "iPhone 15 Pro Max", year: 2023, chip: "Apple A17 Pro",
                    screenSizeInches: 6.7, hasTrueTone: true, hasProMotion: true, hasDynamicIsland: true, hasAlwaysOnDisplay: true,
                    hasFaceID: true, hasTouchID: false, touchIDLocation: .none,
                    rearCameraCount: 3, hasUltraWideCamera: true, hasTelephotoCamera: true, hasMacroCamera: true, hasLiDAR: true, hasOpticalZoom: true,
                    connector: .usbC, supportsMagSafe: true, supportsWirelessCharging: true, supportsFastCharging: true, hasNFC: true, hasUltraWideband: true,
                    hasBarometer: true, hasGyroscope: true, hasCompass: true, hasProximitySensor: true, hasAmbientLightSensor: true,
                    hasActionButton: true, hasHomeButton: false, hasMuteSwitch: false,
                    hasStereoSpeakers: true, microphoneCount: 4),

        // iPhone 16 lineup
        DeviceModel(identifier: "iPhone17,3", marketingName: "iPhone 16", year: 2024, chip: "Apple A18",
                    screenSizeInches: 6.1, hasTrueTone: true, hasProMotion: false, hasDynamicIsland: true, hasAlwaysOnDisplay: true,
                    hasFaceID: true, hasTouchID: false, touchIDLocation: .none,
                    rearCameraCount: 2, hasUltraWideCamera: true, hasTelephotoCamera: false, hasMacroCamera: false, hasLiDAR: false, hasOpticalZoom: false,
                    connector: .usbC, supportsMagSafe: true, supportsWirelessCharging: true, supportsFastCharging: true, hasNFC: true, hasUltraWideband: true,
                    hasBarometer: true, hasGyroscope: true, hasCompass: true, hasProximitySensor: true, hasAmbientLightSensor: true,
                    hasActionButton: true, hasHomeButton: false, hasMuteSwitch: false,
                    hasStereoSpeakers: true, microphoneCount: 3),
        DeviceModel(identifier: "iPhone17,4", marketingName: "iPhone 16 Plus", year: 2024, chip: "Apple A18",
                    screenSizeInches: 6.7, hasTrueTone: true, hasProMotion: false, hasDynamicIsland: true, hasAlwaysOnDisplay: true,
                    hasFaceID: true, hasTouchID: false, touchIDLocation: .none,
                    rearCameraCount: 2, hasUltraWideCamera: true, hasTelephotoCamera: false, hasMacroCamera: false, hasLiDAR: false, hasOpticalZoom: false,
                    connector: .usbC, supportsMagSafe: true, supportsWirelessCharging: true, supportsFastCharging: true, hasNFC: true, hasUltraWideband: true,
                    hasBarometer: true, hasGyroscope: true, hasCompass: true, hasProximitySensor: true, hasAmbientLightSensor: true,
                    hasActionButton: true, hasHomeButton: false, hasMuteSwitch: false,
                    hasStereoSpeakers: true, microphoneCount: 3),
        DeviceModel(identifier: "iPhone17,1", marketingName: "iPhone 16 Pro", year: 2024, chip: "Apple A18 Pro",
                    screenSizeInches: 6.3, hasTrueTone: true, hasProMotion: true, hasDynamicIsland: true, hasAlwaysOnDisplay: true,
                    hasFaceID: true, hasTouchID: false, touchIDLocation: .none,
                    rearCameraCount: 3, hasUltraWideCamera: true, hasTelephotoCamera: true, hasMacroCamera: true, hasLiDAR: true, hasOpticalZoom: true,
                    connector: .usbC, supportsMagSafe: true, supportsWirelessCharging: true, supportsFastCharging: true, hasNFC: true, hasUltraWideband: true,
                    hasBarometer: true, hasGyroscope: true, hasCompass: true, hasProximitySensor: true, hasAmbientLightSensor: true,
                    hasActionButton: true, hasHomeButton: false, hasMuteSwitch: false,
                    hasStereoSpeakers: true, microphoneCount: 4),
        DeviceModel(identifier: "iPhone17,2", marketingName: "iPhone 16 Pro Max", year: 2024, chip: "Apple A18 Pro",
                    screenSizeInches: 6.9, hasTrueTone: true, hasProMotion: true, hasDynamicIsland: true, hasAlwaysOnDisplay: true,
                    hasFaceID: true, hasTouchID: false, touchIDLocation: .none,
                    rearCameraCount: 3, hasUltraWideCamera: true, hasTelephotoCamera: true, hasMacroCamera: true, hasLiDAR: true, hasOpticalZoom: true,
                    connector: .usbC, supportsMagSafe: true, supportsWirelessCharging: true, supportsFastCharging: true, hasNFC: true, hasUltraWideband: true,
                    hasBarometer: true, hasGyroscope: true, hasCompass: true, hasProximitySensor: true, hasAmbientLightSensor: true,
                    hasActionButton: true, hasHomeButton: false, hasMuteSwitch: false,
                    hasStereoSpeakers: true, microphoneCount: 4),
    ]
}
